### ISSUE TITLE
Failure to report errors to the user 

### ISSUE THREAD

**Issue by buckett** [ox-it/wl-feedback#3]
If an submission fails an error should be reported to the user in the interface. Otherwise people will think they have sent feedback but we won't have got it.

**Comment by lardo-de-arnaud** [comment]
It would be useful to state the reason why it failed with a suggestion of what to do – we could fill in the suggestion later if you just add placeholder text.

## 

*\* Note change of email address to adam.marshall@it.ox.ac.ukmailto:adam.marshall@it.ox.ac.uk **

Dr A C Marshall, WebLearn Service Manager, University of Oxford.
IT Services, 13 Banbury Rd, Oxford. OX2 6NN.
