### ISSUE TITLE
When loading feedback over https recaptcha is block

### ISSUE THREAD

**Issue by buckett** [ox-it/wl-feedback#4]
Chrome is block the non-secure recaptcha from being loaded over http when the tool is served over https.

**Comment by ghost** [comment]
This is coming through as

```
<script type="text/javascript" src="://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
```

**Comment by ghost** [comment]
Could I suggest we just use something like `src="//www.google.com/recaptcha/api/js/recaptcha_ajax.js"`?

**Comment by adrianfish** [comment]
Nice one. I didn't know you could get the browser to prepend the page's source protocol like that. You learn something new every day :)
