### ISSUE TITLE
Validate to address is for the site

### ISSUE THREAD

**Issue by buckett** [ox-it/wl-feedback#7]
Could we not accept the To: address from the request parameters and instead just load the contacts from the site when processing the request.

What I'm concerned about is that if someone has a WebLearn account they could use it to send email messages to anyone they like (SPAM) but if we restrict it to just known contacts they can't.

**Comment by adrianfish** [comment]
If we take out the functionality of allowing them to pick one of the maintainers from a list we could probably eliminate all the address passing that happens. We could perhaps, in the absence of the technical contact address being specified, just send the email to all of the maintainers in the site.

**Comment by lardo-de-arnaud** [comment]
I don’t think we can email all maintainers. This would not go down well with them.

Adam

## 

*\* Note change of email address to adam.marshall@it.ox.ac.ukmailto:adam.marshall@it.ox.ac.uk **

Dr A C Marshall, WebLearn Service Manager, University of Oxford.
IT Services, 13 Banbury Rd, Oxford. OX2 6NN.

**Comment by adrianfish** [comment]
How many maintainers do you expect to be in a site? Remember that the list of maintainers is only displayed when no site contact email has been provided; hopefully this eventuality is not very likely.

**Comment by lardo-de-arnaud** [comment]
An average of about 3 or 4. Why you ask?

Adam

On 25 Jun 2014 22:04, Adrian Fish notifications@github.com wrote:

How many maintainers do you expect to be in a site? Remember that the list of maintainers is only displayed when no site contact email has been provided; hopefully this eventuality is not very likely.

**Comment by adrianfish** [comment]
I was just asking because I wondered what the impact would be of just emailing all the maintainers by default.

@buckett Do you mean you are particularly worried that people will just start scripting the system with lists of supplied to addresses? If so I'll just pass the maintainers user ids to the client and resolve them to an email address on the server. In, other words users would only ever be able to send emails to other Sakai users, even if they knew people's user ids. Would that do the trick?

**Comment by buckett** [comment]
The code just accepts any recipient address and doesn't validate that it's actually one of the maintainers.

`toAddress = (String) params.get("contactemail");`

I could supply any address here and WebLearn would send out an email to that person. I just wanted it to validate that the email address used was a maintainer of the site before sending the email.
